stages:
  download:
    cmd: python src/download.py --version 20220301.simple --save_path data/wikipedia_simple_en.hf
    deps:
    - src/download.py
    outs:
    - data/wikipedia_simple_en.hf
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/wikipedia_simple_en.hf
    - src/prepare.py
    outs:
    - data/processed/vocab.txt
    - data/processed/wikipedia_docs.txt
    - data/processed/wikipedia_embeddings.npz
  train:
    cmd: python src/train.py
    deps:
    - data/processed/vocab.txt
    - data/processed/wikipedia_docs.txt
    - data/processed/wikipedia_embeddings.npz
    outs:
    - models/wikipedia_topic_model
